module.exports = {
  users: [
    {
      group_id: 1,
      age: 20,
      gender: 'male',
      watched_movies: '{254, 51253, 33, 1115}',
      action: 50,
      animation: 40,
      comedy: 0,
      documentary: 50,
      drama: 0,
      family: 100,
      fantasy: 30,
      horror: 20,
      international: 50,
      musical: 70,
      mystery: 20,
      romance: 80,
      sci_fi: 15,
      thriller: 0,
      western: 70,
    },
    {
      group_id: 0,
      age: 45,
      gender: 'female',
      watched_movies: '{254, 51253, 33, 1115}',
      action: 40,
      animation: 50,
      comedy: 55,
      documentary: 10,
      drama: 0,
      family: 0,
      fantasy: 60,
      horror: 20,
      international: 50,
      musical: 30,
      mystery: 56,
      romance: 72,
      sci_fi: 22,
      thriller: 34,
      western: 15,
    },
    {
      group_id: 1,
      age: 19,
      gender: 'male',
      watched_movies: '{112, 15346, 853, 2}',
      action: 10,
      animation: 10,
      comedy: 20,
      documentary: 30,
      drama: 0,
      family: 40,
      fantasy: 78,
      horror: 9,
      international: 6,
      musical: 37,
      mystery: 15,
      romance: 22,
      sci_fi: 11,
      thriller: 0,
      western: 0,
    },
    {
      group_id: 0,
      age: 44,
      gender: 'female',
      watched_movies: '{254, 1, 33, 15, 2324}',
      action: 0,
      animation: 0,
      comedy: 0,
      documentary: 30,
      drama: 40,
      family: 40,
      fantasy: 0,
      horror: 0,
      international: 0,
      musical: 60,
      mystery: 0,
      romance: 0,
      sci_fi: 0,
      thriller: 0,
      western: 0,
    },
    {
      group_id: 1,
      age: 24,
      gender: 'male',
      watched_movies: '{325}',
      action: 20,
      animation: 60,
      comedy: 10,
      documentary: 20,
      drama: 55,
      family: 45,
      fantasy: 20,
      horror: 32,
      international: 65,
      musical: 53,
      mystery: 67,
      romance: 54,
      sci_fi: 20,
      thriller: 50,
      western: 60,
    },
  ],
  movies: [
    {
      userId: 1,
      id: 23525,
      profile: JSON.stringify({
        action: 0,
        animation: 0,
        comedy: 0,
        documentary: 0,
        drama: 40,
        family: 0,
        fantasy: 0,
        horror: 0,
        international: 0,
        musical: 0,
        mystery: 30,
        romance: 0,
        sci_fi: 0,
        thriller: 30,
        western: 0,
      }),
      startTime: '2017-10-23 08:00:00',
    },
    {
      userId: 2,
      id: 325362,
      profile: JSON.stringify({
        action: 0,
        animation: 0,
        comedy: 0,
        documentary: 0,
        drama: 0,
        family: 100,
        fantasy: 0,
        horror: 0,
        international: 0,
        musical: 0,
        mystery: 0,
        romance: 0,
        sci_fi: 0,
        thriller: 0,
        western: 0,
      }),
      startTime: '2017-10-23 09:00:00',
    },
    {
      userId: 3,
      id: 623452,
      profile: JSON.stringify({
        action: 50,
        animation: 0,
        comedy: 50,
        documentary: 0,
        drama: 0,
        family: 0,
        fantasy: 0,
        horror: 0,
        international: 0,
        musical: 0,
        mystery: 0,
        romance: 0,
        sci_fi: 0,
        thriller: 0,
        western: 0,
      }),
      startTime: '2017-10-23 10:00:00',
    },
  ],
};
